py27 develop-inst-nodeps: /home/ubuntu/client-tags
py27 installed: alabaster==0.7.10,appdirs==1.4.3,asn1crypto==0.22.0,Babel==2.3.4,bandit==1.4.0,bcrypt==3.1.3,certifi==2017.4.17,cffi==1.10.0,chardet==3.0.4,cliff==2.8.0,cmd2==0.7.5,coverage==4.4.1,cryptography==1.9,debtcollector==1.16.0,docutils==0.13.1,dulwich==0.17.3,enum34==1.1.6,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.2.4,flake8-docstrings==0.2.1.post1,funcsigs==1.0.2,functools32==3.2.3.post2,gitdb2==2.0.2,GitPython==2.1.5,hacking==0.10.3,idna==2.5,imagesize==0.7.1,ipaddress==1.0.18,iso8601==0.1.11,Jinja2==2.9.6,jsonschema==2.6.0,keyring==10.4.0,keystoneauth1==2.21.0,linecache2==1.0.0,lxml==3.8.0,MarkupSafe==1.0,mccabe==0.2.1,mock==2.0.0,monotonic==1.3,mox3==0.22.0,msgpack-python==0.4.8,netaddr==0.7.19,netifaces==0.10.6,oauthlib==2.0.2,openstack-requirements==1.0.0,openstackdocstheme==1.13.0,os-client-config==1.28.0,os-testr==0.8.2,oslo.concurrency==3.20.0,oslo.config==4.8.0,oslo.context==2.16.0,oslo.i18n==3.16.0,oslo.log==3.29.0,oslo.serialization==2.19.0,oslo.utils==3.27.0,oslotest==2.16.1,packaging==16.8,paramiko==2.2.1,Parsley==1.3,pbr==3.1.1,pep257==0.7.0,pep8==1.5.7,positional==1.1.1,prettytable==0.7.2,pyasn1==0.2.2,pycparser==2.18,pyflakes==0.8.1,Pygments==2.2.0,pyinotify==0.9.6,PyNaCl==1.1.2,pyparsing==2.2.0,pyperclip==1.5.27,python-dateutil==2.6.1,-e git+https://github.com/jessegler/python-keystoneclient.git@84b486eb5a5d8a3773acb7bca7c8b6946acf3788#egg=python_keystoneclient,python-mimeparse==1.6.0,python-subunit==1.2.0,pytz==2017.2,PyYAML==3.12,reno==2.4.1,requests==2.18.1,requests-mock==1.3.0,requestsexceptions==1.3.0,rfc3986==1.0.0,SecretStorage==2.3.1,six==1.10.0,smmap2==2.0.3,snowballstemmer==1.2.1,Sphinx==1.6.3,sphinxcontrib-websupport==1.0.1,stevedore==1.24.0,tempest==16.1.0,testrepository==0.0.20,testresources==2.0.1,testscenarios==0.5.0,testtools==2.3.0,traceback2==1.4.0,typing==3.6.1,unicodecsv==0.14.1,unittest2==1.1.0,urllib3==1.21.1,wrapt==1.10.10
py27 runtests: PYTHONHASHSEED='2816248064'
py27 runtests: commands[0] | find . -type f -name *.pyc -delete
py27 runtests: commands[1] | python setup.py testr --slowest --testr-args=
running testr
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py:1049: DeprecationWarning: Using function/method 'keystoneclient.auth.conf.load_from_conf_options()' is deprecated in version '2.1.0' and will be removed in version '3.0.0': keystoneclient auth plugins are deprecated. Use keystoneauth.
  return self._callable_object(*self._args, **self._kwargs)
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/keystoneauth1/adapter.py:149: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
  warnings.warn('Using keystoneclient sessions has been deprecated. '
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/keystoneauth1/adapter.py:149: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
  warnings.warn('Using keystoneclient sessions has been deprecated. '
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py:1049: DeprecationWarning: Using function/method 'HTTPClient.get()' is deprecated in version '1.7.0' and will be removed in version '2.0.0'
  return self._callable_object(*self._args, **self._kwargs)
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py:1049: DeprecationWarning: Using function/method 'HTTPClient.post()' is deprecated in version '1.7.0' and will be removed in version '2.0.0'
  return self._callable_object(*self._args, **self._kwargs)
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py:1049: DeprecationWarning: Using function/method 'HTTPClient.put()' is deprecated in version '1.7.0' and will be removed in version '2.0.0'
  return self._callable_object(*self._args, **self._kwargs)
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py:1049: DeprecationWarning: Using function/method 'HTTPClient.delete()' is deprecated in version '1.7.0' and will be removed in version '2.0.0'
  return self._callable_object(*self._args, **self._kwargs)
/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/six.py:671: PendingDeprecationWarning: Please use assertRaisesRegex instead.
  return getattr(self, _assertRaisesRegex)(*args, **kwargs)
running=${PYTHON:-python} -m subunit.run discover -t ./  ${OS_TEST_PATH:-./keystoneclient/tests/unit} --list 
running=${PYTHON:-python} -m subunit.run discover -t ./  ${OS_TEST_PATH:-./keystoneclient/tests/unit}  --load-list /tmp/tmp4aUZHE
running=${PYTHON:-python} -m subunit.run discover -t ./  ${OS_TEST_PATH:-./keystoneclient/tests/unit}  --load-list /tmp/tmpdj2tvU
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_create(original)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 240, in test_create
    returned = self.manager.create(**parameterize(manager_ref))
  File "/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
TypeError: create() takes at least 2 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_create(ksc-session)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 240, in test_create
    returned = self.manager.create(**parameterize(manager_ref))
  File "/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
TypeError: create() takes at least 2 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_create(ksa-session)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 240, in test_create
    returned = self.manager.create(**parameterize(manager_ref))
  File "/home/ubuntu/client-tags/.tox/py27/local/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
TypeError: create() takes at least 2 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_delete(original)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 373, in test_delete
    self.manager.delete(ref['id'])
TypeError: delete() takes exactly 3 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_delete(ksc-session)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 373, in test_delete
    self.manager.delete(ref['id'])
TypeError: delete() takes exactly 3 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_delete(ksa-session)
tags: worker-0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 373, in test_delete
    self.manager.delete(ref['id'])
TypeError: delete() takes exactly 3 arguments (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_check_in_project(original)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/test_project_tags.py", line 120, in test_check_in_project
    self.assertTrue(self.manager.check_in_project(project, tag_id))
NameError: global name 'tag_id' is not defined
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_check_in_project(ksc-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/test_project_tags.py", line 120, in test_check_in_project
    self.assertTrue(self.manager.check_in_project(project, tag_id))
NameError: global name 'tag_id' is not defined
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_check_in_project(ksa-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/test_project_tags.py", line 120, in test_check_in_project
    self.assertTrue(self.manager.check_in_project(project, tag_id))
NameError: global name 'tag_id' is not defined
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_get(original)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 257, in test_get
    returned = self.manager.get(ref['id'])
  File "keystoneclient/base.py", line 75, in func
    return f(*args, **new_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_get(ksc-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 257, in test_get
    returned = self.manager.get(ref['id'])
  File "keystoneclient/base.py", line 75, in func
    return f(*args, **new_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_get(ksa-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 257, in test_get
    returned = self.manager.get(ref['id'])
  File "keystoneclient/base.py", line 75, in func
    return f(*args, **new_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list(original)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 297, in test_list
    returned_list = self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list(ksc-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 297, in test_list
    returned_list = self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list(ksa-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 297, in test_list
    returned_list = self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list_params(original)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 323, in test_list_params
    self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list_params(ksc-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 323, in test_list_params
    self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_list_params(ksa-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 323, in test_list_params
    self.manager.list(**filter_kwargs)
TypeError: list() takes exactly 2 arguments (1 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_update(original)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 360, in test_update
    returned = self.manager.update(ref['id'], **parameterize(req_ref))
TypeError: update() takes at least 3 arguments (3 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_update(ksc-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 360, in test_update
    returned = self.manager.update(ref['id'], **parameterize(req_ref))
TypeError: update() takes at least 3 arguments (3 given)
======================================================================
FAIL: keystoneclient.tests.unit.v3.test_project_tags.ProjectTagsTests.test_update(ksa-session)
tags: worker-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/utils.py", line 360, in test_update
    returned = self.manager.update(ref['id'], **parameterize(req_ref))
TypeError: update() takes at least 3 arguments (3 given)
Ran 1768 (+3) tests in 4.766s (-0.150s)
FAILED (id=3, failures=21 (+3), skips=4)
error: testr failed (1)
ERROR: InvocationError: '/home/ubuntu/client-tags/.tox/py27/bin/python setup.py testr --slowest --testr-args='
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
